### ISSUE TITLE
Access denied on Windows while attempting to lock

### ISSUE THREAD

**Issue by raycoe** [kalamay/file-guard#2]
Hi,

When `file_guard::lock(&file, Lock::Exclusive, 0, 1)`, get error  **Access is denied. (os error 5)** on Windows despite `Everyone` is granted full access on the target folder and inner files.

Works on MacOS and Linux, but not on Windows apparently

**Comment by kalamay** [comment]
Hi @raycoe thanks for reporting. What version of windows are you on? I'll take a look on windows 11 soon, but do you have any more details about your issue? Does this fall on all uses?

**Comment by raycoe** [comment]
Hi,

It is Windows 10 64bits, last updates installed.

For info, I found a workaround by adding .read(true) to the file attributes. Would it mean that Windows requires this attribute on top of the others to properly determine if you've got enough permissions?

KR
Ray
